version: '3'

services:
  fastapi_app:
    build: .
    ports:
      - "8080:8000"  # Map port 8000 in the container to port 8080 on the host for FastAPI
    networks:
      - scripts3_default

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"  # Map port 9090 in the container to port 9091 on the host for Prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - scripts3_default

networks:
  scripts3_default:
